#!/bin/bash
# =============================================================================
# Sprout OS Orbit — Full QA Orchestrator
# Runs all 11 individual QA scripts and generates a release gate summary
#
# Usage:
#   bash scripts/run-full-qa.sh            # run all 11 areas
#   bash scripts/run-full-qa.sh --quick    # skip Lighthouse-heavy checks
# =============================================================================

if [ -f .env ]; then
  export $(grep -v '^#' .env | xargs)
fi

QUICK=false
FAILED=0
PASSED=0
TIMESTAMP=$(date +"%Y-%m-%d_%H-%M-%S")
REPORT_DIR="reports/full-qa"
SUMMARY_FILE="$REPORT_DIR/qa-release-gate-$TIMESTAMP.md"

for arg in "$@"; do
  case $arg in
    --quick) QUICK=true ;;
  esac
done

mkdir -p "$REPORT_DIR"

echo ""
echo "╔══════════════════════════════════════════════════════╗"
echo "║     Sprout OS Orbit — Full QA Orchestrator           ║"
echo "║     11 Areas · Release Gate                          ║"
echo "╚══════════════════════════════════════════════════════╝"
echo ""
echo " Mode    : $([ "$QUICK" = true ] && echo 'Quick (Lighthouse skipped)' || echo 'Full')"
echo " Started : $TIMESTAMP"
echo ""

# ── Runner helper ──────────────────────────────────────────────────────────
run_area() {
  local AREA_NUM=$1
  local AREA_NAME=$2
  local SCRIPT=$3
  shift 3
  local EXTRA_ARGS=("$@")

  echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
  echo " AREA $AREA_NUM — $AREA_NAME"
  echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

  if [ ! -f "$SCRIPT" ]; then
    echo " SKIP — script not found: $SCRIPT"
    echo ""
    RESULTS+=("| ⏭ SKIP | $AREA_NAME |")
    return
  fi

  bash "$SCRIPT" "${EXTRA_ARGS[@]}"

  if [ $? -eq 0 ]; then
    echo " PASSED: $AREA_NAME"
    PASSED=$((PASSED + 1))
    RESULTS+=("| ✅ PASS | $AREA_NAME |")
  else
    echo " FAILED: $AREA_NAME"
    FAILED=$((FAILED + 1))
    RESULTS+=("| ❌ FAIL | $AREA_NAME |")
  fi

  echo ""
}

declare -a RESULTS=()

# ── Run all 11 QA areas ───────────────────────────────────────────────────
run_area  1  "UI / UX"              "scripts/qa-ui.sh"
run_area  2  "Functionality"        "scripts/qa-functionality.sh"
run_area  3  "Responsiveness"       "scripts/qa-responsive.sh"
run_area  4  "Logic / Business Rules" "scripts/qa-logic.sh"
run_area  5  "Security"             "scripts/qa-security.sh"

if [ "$QUICK" = true ]; then
  echo " AREA 6 — Performance — SKIPPED (--quick mode)"
  RESULTS+=("| ⏭ SKIP | Performance (--quick) |")
else
  run_area  6  "Performance"          "scripts/qa-performance.sh"
fi

run_area  7  "Accessibility"        "scripts/qa-accessibility.sh"
run_area  8  "Cross-Browser"        "scripts/qa-cross-browser.sh"
run_area  9  "Console Errors"       "scripts/qa-console.sh"
run_area 10  "SEO / Meta Tags"      "scripts/qa-seo.sh"
run_area 11  "Code Quality"         "scripts/qa-code-quality.sh"

# ── Generate release gate summary ────────────────────────────────────────
TOTAL=$((PASSED + FAILED))

cat > "$SUMMARY_FILE" <<MDEOF
# Sprout OS — QA Release Gate

**Date:** $(date)
**Run ID:** $TIMESTAMP
**Mode:** $([ "$QUICK" = true ] && echo "Quick" || echo "Full")

---

## Results

| Status | QA Area |
|--------|---------|
$(for r in "${RESULTS[@]}"; do echo "$r"; done)

---

## Score

- **Areas completed:** $TOTAL / 11
- **Passed:** $PASSED
- **Failed:** $FAILED
- **Pass rate:** $(echo "scale=0; $PASSED * 100 / ($TOTAL > 0 && $TOTAL || 1)" | bc 2>/dev/null || echo "N/A")%

---

## Release Decision

$(if [ $FAILED -eq 0 ]; then
  echo "### ✅ RELEASE APPROVED"
  echo ""
  echo "All QA areas passed. This build is cleared for release."
else
  echo "### ❌ RELEASE BLOCKED"
  echo ""
  echo "$FAILED area(s) failed. Review failures above before releasing."
fi)

---

## Quick Commands

\`\`\`bash
# Re-run individual areas
bash scripts/qa-ui.sh
bash scripts/qa-functionality.sh
bash scripts/qa-responsive.sh
bash scripts/qa-logic.sh
bash scripts/qa-security.sh
bash scripts/qa-performance.sh
bash scripts/qa-accessibility.sh
bash scripts/qa-cross-browser.sh
bash scripts/qa-console.sh
bash scripts/qa-seo.sh
bash scripts/qa-code-quality.sh

# View Playwright HTML report
npx playwright show-report

# Full run (next time)
bash scripts/run-full-qa.sh
\`\`\`

---

*Generated by Sprout OS Orbit QA Orchestrator — $(date)*
MDEOF

# ── Final output ─────────────────────────────────────────────────────────
echo "╔══════════════════════════════════════════════════════╗"
echo "║             RELEASE GATE SUMMARY                     ║"
echo "╚══════════════════════════════════════════════════════╝"
echo ""
echo " Completed : $(date +"%Y-%m-%d %H:%M:%S")"
echo " Passed    : $PASSED"
echo " Failed    : $FAILED"
echo " Report    : $SUMMARY_FILE"
echo ""

if [ $FAILED -eq 0 ]; then
  echo " ✅ ALL QA AREAS PASSED — RELEASE APPROVED"
  echo " View report: npx playwright show-report"
  exit 0
else
  echo " ❌ $FAILED AREA(S) FAILED — RELEASE BLOCKED"
  echo " View report: npx playwright show-report"
  exit 1
fi
